# -*- coding: utf-8 -*-
"""mobi_physiov2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xxa-dPIvAfBjsfFlvQ5_sx8Rwx4lVa7
"""

# MobiPhysio -> feature DB (Colab) — v2 (MobiPhysio 전용)
# =====================================================================
# 변경점(v1 대비): Harvard Dataverse(API)로 subset 자동 다운로드 +
#   MobiPhysio 실제 파일명 규칙 파싱 + 평가점수 CSV로 정상/비정상 라벨.
# 산출물: mobiphysio_features.sqlite (UI-PRMD features.sqlite 와 동일 3-테이블)
# 데이터: doi:10.7910/DVN/XSI0QN  (CC BY)
#   파일명 규칙(Table 2): E01 P01 A F V FL G M
#     Exercise(E01~E09) / Participant(P..) / Angle(F,L,R) / Variation / Gender(M,F)
#   운동: E01 Abduction, E02 Adduction, E03 Lateral Rotation, E04 Medial Rotation,
#         E05 Circumduction, E06 Wrist Extension, E07 Hip Joint Flexion,
#         E08 Lumber Flexion, E09 Back Extension
# =====================================================================

# %% [Cell 1] 의존성 -----------------------------------------------------
!pip -q install "mediapipe>=0.10,<0.11" opencv-python-headless pandas pyarrow tqdm requests

# import requests
# PID='doi:10.7910/DVN/XSI0QN'; BASE='https://dataverse.harvard.edu'
# r=requests.get(f'{BASE}/api/datasets/:persistentId/',
#                params={'persistentId':PID},
#                headers={'User-Agent':'Mozilla/5.0'}, timeout=90)
# print('status:', r.status_code, '| ctype:', r.headers.get('content-type'))
# print(r.text[:400])

# # %% [Cell 2] Drive 마운트 + Dataverse subset 다운로드 -------------------
# from google.colab import drive
# drive.mount('/content/drive')

# import os, re, requests
# from tqdm.auto import tqdm

# # ---- CONFIG ----------------------------------------------------------
# PID      = 'doi:10.7910/DVN/XSI0QN'
# BASE     = 'https://dataverse.harvard.edu'
# DATA_DIR = '/content/mobiphysio'                      # 영상 받을 임시 위치(Colab)
# OUT_DIR  = '/content/drive/MyDrive/alignfit/mobiphysio'  # 결과 저장(Drive)
# os.makedirs(DATA_DIR, exist_ok=True)
# os.makedirs(OUT_DIR, exist_ok=True)
# PROGRESS_CSV = os.path.join(OUT_DIR, 'features_progress.csv')
# OUT_SQLITE   = os.path.join(OUT_DIR, 'mobiphysio_features.sqlite')

# # subset 규칙 (속도/용량 조절)
# ANGLE_KEEP       = {'F'}   # 정면만. 좌우도 쓰려면 {'F','L','R'}
# MAX_PER_EXERCISE = 80      # 운동당 최대 영상 수 (None=전체)
# RANDOM_SEED      = 42
# # ----------------------------------------------------------------------

# import numpy as np
# rng = np.random.default_rng(RANDOM_SEED)

# # 1) 저장소 파일 목록
# import time
# HEADERS = {'User-Agent': 'Mozilla/5.0'}

# def get_json(url, params, tries=4):
#     r = None
#     for i in range(tries):
#         r = requests.get(url, params=params, headers=HEADERS, timeout=120)
#         if r.status_code == 200 and 'json' in r.headers.get('content-type', ''):
#             return r.json()
#         print(f'  try {i+1}: status {r.status_code} -> 재시도')
#         time.sleep(5 * (i + 1))
#     raise RuntimeError(f'실패: {r.status_code} {r.text[:200]}')

# def list_files(limit=500):
#     out, offset = [], 0
#     while True:
#         d = get_json(f'{BASE}/api/datasets/:persistentId/versions/:latest/files',
#                      {'persistentId': PID, 'limit': limit, 'offset': offset})['data']
#         if not d:
#             break
#         out += d
#         offset += len(d)
#         print('  fetched', offset)
#         if len(d) < limit:
#             break
#     return out

# files = list_files()           # 페이지 단위로 안전하게 수집
# print('repo 총 파일 수:', len(files))
# print('repo 총 파일 수:', len(files))

# def finfo(f):
#     df = f['dataFile']
#     return df['id'], df.get('filename', f.get('label', ''))

# # 파일명 파서 (구분자가 있든 없든 동작하도록 정규식)
# def parse_name(fn):
#     b = os.path.splitext(fn)[0]
#     ex  = re.search(r'E(\d{2})', b)
#     pid = re.search(r'P(\d{2,3})', b)
#     ang = re.search(r'A[\s_]?([FLR])', b)
#     gen = re.search(r'G[\s_]?([MF])', b)
#     return (f'E{ex.group(1)}' if ex else None,
#             f'P{pid.group(1)}' if pid else None,
#             ang.group(1) if ang else None,
#             gen.group(1) if gen else None)

# # 2) 영상/CSV 분류 + subset 선정
# vids, score_csv = [], None
# for f in files:
#     fid, fn = finfo(f)
#     low = fn.lower()
#     if low.endswith('.csv'):
#         score_csv = (fid, fn)            # 평가점수 CSV 후보
#     elif low.endswith(('.mp4', '.avi', '.mov', '.mkv')):
#         ex, pid_, ang, gen = parse_name(fn)
#         if ex and (ang in ANGLE_KEEP if ang else True):
#             vids.append(dict(fid=fid, fn=fn, exercise=ex, subject=pid_,
#                              angle=ang, gender=gen))

# print('정면(또는 조건) 영상 후보:', len(vids), '| 점수 CSV:', score_csv[1] if score_csv else None)
# print('파일명 샘플:', [v['fn'] for v in vids[:5]])   # 파서 동작 눈으로 확인

# # 운동당 균형 subsample
# import pandas as pd
# vdf = pd.DataFrame(vids)
# if MAX_PER_EXERCISE:
#     vdf = (vdf.groupby('exercise', group_keys=False)
#               .apply(lambda g: g.sample(min(len(g), MAX_PER_EXERCISE), random_state=RANDOM_SEED)))
# vdf = vdf.reset_index(drop=True)
# print('다운로드할 영상 수:', len(vdf))
# print(vdf.groupby('exercise').size())

# # 3) 다운로드 (이미 받은 건 skip)
# def download(fid, fn, dst):
#     if os.path.exists(dst) and os.path.getsize(dst) > 0:
#         return
#     url = f'{BASE}/api/access/datafile/{fid}'
#     with requests.get(url, stream=True, timeout=300, headers=HEADERS) as r:
#         r.raise_for_status()
#         with open(dst, 'wb') as out:
#             for chunk in r.iter_content(1 << 20):
#                 out.write(chunk)

# for _, v in tqdm(vdf.iterrows(), total=len(vdf), desc='download'):
#     download(v['fid'], v['fn'], os.path.join(DATA_DIR, v['fn']))

# # 점수 CSV 도 받기
# SCORE_CSV_PATH = None
# if score_csv:
#     SCORE_CSV_PATH = os.path.join(DATA_DIR, score_csv[1])
#     download(score_csv[0], score_csv[1], SCORE_CSV_PATH)
#     print('점수 CSV 저장:', SCORE_CSV_PATH)

import time
HEADERS = {'User-Agent': 'Mozilla/5.0'}

def download(fid, fn, dst, tries=5):
    if os.path.exists(dst) and os.path.getsize(dst) > 0:
        return True
    url = f'{BASE}/api/access/datafile/{fid}'
    for i in range(tries):
        try:
            with requests.get(url, stream=True, timeout=300, headers=HEADERS) as r:
                if r.status_code != 200:
                    time.sleep(5 * (i + 1)); continue
                with open(dst, 'wb') as out:
                    for ch in r.iter_content(1 << 20):
                        out.write(ch)
            if os.path.getsize(dst) > 0:
                return True
        except Exception:
            time.sleep(5 * (i + 1))
    if os.path.exists(dst) and os.path.getsize(dst) == 0:
        os.remove(dst)   # 깨진 부분 파일 제거
    return False

failed = []
for _, v in tqdm(vdf.iterrows(), total=len(vdf), desc='download'):
    if not download(v['fid'], v['fn'], os.path.join(DATA_DIR, v['fn'])):
        failed.append(v['fn'])
print('다운로드 완료. 실패(스킵):', len(failed))

# 점수 CSV 받기
SCORE_CSV_PATH = None
if score_csv:
    SCORE_CSV_PATH = os.path.join(DATA_DIR, score_csv[1])
    download(score_csv[0], score_csv[1], SCORE_CSV_PATH)
    print('점수 CSV:', SCORE_CSV_PATH)

# %% [Cell 3] rec_df 구성 (MobiPhysio 점수 CSV 구조 반영)
EX_NAME = {'E01':'Abduction','E02':'Adduction','E03':'Lateral Rotation',
           'E04':'Medial Rotation','E05':'Circumduction','E06':'Wrist Extension',
           'E07':'Hip Joint Flexion','E08':'Lumber Flexion','E09':'Back Extension'}
EX_REGION = {'E01':'upper_shoulder','E02':'upper_shoulder','E03':'upper_shoulder',
             'E04':'upper_shoulder','E05':'upper_shoulder','E06':'upper_wrist',
             'E07':'lower_hip','E08':'low_back','E09':'low_back'}

# 점수: 'Video Name' 있는 행만(=영상 대표행), 점수는 Unnamed:12(반올림 평균)->없으면 Unnamed:11
score_map = {}
if SCORE_CSV_PATH and os.path.exists(SCORE_CSV_PATH):
    sdf = pd.read_csv(SCORE_CSV_PATH)
    sdf = sdf[sdf['Video Name'].notna()].copy()
    def _score(r):
        for c in ['Unnamed: 12', 'Unnamed: 11']:
            try:
                v = float(r[c])
                if not np.isnan(v): return v
            except Exception: pass
        return np.nan
    for _, r in sdf.iterrows():
        s = _score(r)
        if not np.isnan(s):
            score_map[str(r['Video Name']).strip().lower()] = s
    print('점수 매핑된 영상 수:', len(score_map))
    print('예시:', list(score_map.items())[:3])

SCORE_CUTOFF = None   # None=중앙값 분할(클래스 균형). 고정 임계값 원하면 예: 80

recs = []
for _, v in vdf.iterrows():
    key = os.path.splitext(v['fn'])[0].lower()
    recs.append(dict(video_path=os.path.join(DATA_DIR, v['fn']),
                     exercise_id=v['exercise'],
                     exercise_name=EX_NAME.get(v['exercise'], v['exercise']),
                     subject_id=v['subject'], region=EX_REGION.get(v['exercise'], 'upper'),
                     score=score_map.get(key, np.nan)))
rec_df = pd.DataFrame(recs)

if score_map:
    n0 = len(rec_df); rec_df = rec_df.dropna(subset=['score']).reset_index(drop=True)
    print(f'점수 매칭: {len(rec_df)}/{n0}')
    cutoff = SCORE_CUTOFF if SCORE_CUTOFF is not None else rec_df['score'].median()
    print('cutoff =', cutoff)
    rec_df['label_binary'] = (rec_df['score'] < cutoff).astype(int)   # 낮으면 비정상=1
else:
    print('!! 점수 매핑 실패'); rec_df['label_binary'] = 0

rec_df['correctness']    = rec_df['label_binary'].map({0:'correct',1:'incorrect'})
ex_order = sorted(rec_df['exercise_id'].unique())
rec_df['label_exercise'] = rec_df['exercise_id'].map({e:i for i,e in enumerate(ex_order)})
rec_df['seq_id']         = [f'mp_{i:05d}' for i in range(len(rec_df))]

subs = sorted(rec_df['subject_id'].dropna().unique()); rng.shuffle(subs)
n=len(subs); n_tr=int(n*0.6); n_va=int(n*0.2)
smap={s:('train' if i<n_tr else ('val' if i<n_tr+n_va else 'test')) for i,s in enumerate(subs)}
rec_df['split']=rec_df['subject_id'].map(smap)
print('subjects:', n)
print(rec_df.groupby(['split','label_binary']).size())

import mediapipe as mp
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision
import urllib.request

MODEL_PATH = '/content/pose_landmarker_lite.task'
if not os.path.exists(MODEL_PATH):
    urllib.request.urlretrieve(
        'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task',
        MODEL_PATH)

_opts = vision.PoseLandmarkerOptions(
    base_options=mp_python.BaseOptions(model_asset_path=MODEL_PATH),
    running_mode=vision.RunningMode.IMAGE, num_poses=1,
    min_pose_detection_confidence=0.5, min_pose_presence_confidence=0.5)
landmarker = vision.PoseLandmarker.create_from_options(_opts)
MIN_VISIBILITY = 0.5; FRAME_STRIDE = 2

L = dict(nose=0, l_ear=7, r_ear=8, l_sho=11, r_sho=12, l_elb=13, r_elb=14,
         l_wri=15, r_wri=16, l_idx=19, r_idx=20, l_hip=23, r_hip=24,
         l_kne=25, r_kne=26, l_ank=27, r_ank=28)
ANGLES = [
    ('l_elbow',('l_sho','l_elb','l_wri'),'upper'), ('r_elbow',('r_sho','r_elb','r_wri'),'upper'),
    ('l_shoulder',('l_hip','l_sho','l_elb'),'upper'), ('r_shoulder',('r_hip','r_sho','r_elb'),'upper'),
    ('l_armpit',('l_elb','l_sho','r_sho'),'upper'), ('r_armpit',('r_elb','r_sho','l_sho'),'upper'),
    ('l_wrist',('l_elb','l_wri','l_idx'),'upper'), ('r_wrist',('r_elb','r_wri','r_idx'),'upper'),
    ('l_hip',('l_sho','l_hip','l_kne'),'lower'), ('r_hip',('r_sho','r_hip','r_kne'),'lower'),
    ('l_knee',('l_hip','l_kne','l_ank'),'lower'), ('r_knee',('r_hip','r_kne','r_ank'),'lower'),
    ('neck_tilt',('l_ear','nose','r_ear'),'upper'),
    ('trunk_l',('l_sho','l_hip','r_hip'),'lower'), ('trunk_r',('r_sho','r_hip','l_hip'),'lower'),
]
STATS = ['mean','std','range','max']
SYM_PAIRS = [('sym_elbow','l_elbow','r_elbow'),('sym_shoulder','l_shoulder','r_shoulder'),
             ('sym_armpit','l_armpit','r_armpit'),('sym_wrist','l_wrist','r_wrist'),
             ('sym_hip','l_hip','r_hip'),('sym_knee','l_knee','r_knee'),
             ('sym_trunk','trunk_l','trunk_r')]

def _angle(a,b,c):
    ba,bc=a-b,c-b; nba,nbc=np.linalg.norm(ba),np.linalg.norm(bc)
    if nba<1e-6 or nbc<1e-6: return np.nan
    return np.degrees(np.arccos(np.clip(np.dot(ba,bc)/(nba*nbc),-1,1)))

def clip_features(coords):
    arr=np.stack(coords,0); T=arr.shape[0]
    ang={n:np.full(T,np.nan) for n,_,_ in ANGLES}
    for t in range(T):
        xy,vis=arr[t,:,:2],arr[t,:,2]
        for n,(a,b,c),_ in ANGLES:
            ia,ib,ic=L[a],L[b],L[c]
            if min(vis[ia],vis[ib],vis[ic])>=MIN_VISIBILITY:
                ang[n][t]=_angle(xy[ia],xy[ib],xy[ic])
    f={}
    for n,_,_ in ANGLES:
        v=ang[n]; ok=np.any(~np.isnan(v))
        f[f'{n}_mean']=np.nanmean(v) if ok else 0.0
        f[f'{n}_std'] =np.nanstd(v)  if ok else 0.0
        f[f'{n}_range']=(np.nanmax(v)-np.nanmin(v)) if ok else 0.0
        f[f'{n}_max'] =np.nanmax(v)  if ok else 0.0
    for sn,ln,rn in SYM_PAIRS:
        d=np.abs(ang[ln]-ang[rn]); f[sn]=np.nanmean(d) if np.any(~np.isnan(d)) else 0.0
    f['sym_shoulder_h']=float(np.nanmean(np.abs(arr[:,L['l_sho'],1]-arr[:,L['r_sho'],1])))
    f['sym_hip_h']     =float(np.nanmean(np.abs(arr[:,L['l_hip'],1]-arr[:,L['r_hip'],1])))
    return f,T

FEATURE_ORDER,FEATURE_META=[],[]
for n,_,g in ANGLES:
    for st in STATS: FEATURE_ORDER.append(f'{n}_{st}'); FEATURE_META.append((f'{n}_{st}',st,g))
for sn,_,_ in SYM_PAIRS: FEATURE_ORDER.append(sn); FEATURE_META.append((sn,'symdiff','symmetry'))
for sn in ['sym_shoulder_h','sym_hip_h']: FEATURE_ORDER.append(sn); FEATURE_META.append((sn,'heightdiff','symmetry'))
print('피처 차원:', len(FEATURE_ORDER))

import cv2
done = set()
if os.path.exists(PROGRESS_CSV):
    done = set(pd.read_csv(PROGRESS_CSV)['seq_id'].astype(str)); print('재개:', len(done))
todo = rec_df[~rec_df['seq_id'].isin(done)]; print('처리할 클립:', len(todo))

for _, row in tqdm(todo.iterrows(), total=len(todo)):
    coords = []
    cap = cv2.VideoCapture(row['video_path']); fi = 0
    while True:
        ok, fr = cap.read()
        if not ok: break
        if fi % FRAME_STRIDE == 0:
            rgb = cv2.cvtColor(fr, cv2.COLOR_BGR2RGB)
            mp_img = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
            res = landmarker.detect(mp_img)
            if res.pose_landmarks:
                lm = res.pose_landmarks[0]
                coords.append(np.array([[p.x, p.y, p.visibility] for p in lm]))
        fi += 1
    cap.release()
    if len(coords) < 3: continue
    feats, T = clip_features(coords)
    out = {'seq_id': row['seq_id'], 'n_frames': int(T)}
    for k in FEATURE_ORDER: out[k] = float(feats.get(k, 0.0))
    pd.DataFrame([out]).to_csv(PROGRESS_CSV, mode='a',
                               header=not os.path.exists(PROGRESS_CSV), index=False)
print('추출 완료:', PROGRESS_CSV)

# %% [Cell 6] features.sqlite 동일 구조 패키징 + 다운로드 ---------------
import sqlite3
feat=pd.read_csv(PROGRESS_CSV).drop_duplicates('seq_id',keep='last')
meta_cols=['seq_id','exercise_id','exercise_name','subject_id','correctness',
           'label_binary','label_exercise','region','split']
meta_df=rec_df[meta_cols].merge(feat[['seq_id','n_frames']],on='seq_id')
fcols={old:f'f{i:03d}' for i,old in enumerate(FEATURE_ORDER)}
summ_df=feat[['seq_id']+FEATURE_ORDER].rename(columns=fcols)
summ_df=summ_df[summ_df['seq_id'].isin(meta_df['seq_id'])].reset_index(drop=True)
fname_df=pd.DataFrame([{'idx':i,'feat_col':f'f{i:03d}','name':nm,'stat':st,'group':gp}
                       for i,(nm,st,gp) in enumerate(FEATURE_META)])

con=sqlite3.connect(OUT_SQLITE)
meta_df.to_sql('sequence_meta',con,if_exists='replace',index=False)
summ_df.to_sql('summary_features',con,if_exists='replace',index=False)
fname_df.to_sql('feature_names',con,if_exists='replace',index=False)
con.close()
print('저장:', OUT_SQLITE, '| clips:', len(meta_df), '| dim:', len(FEATURE_ORDER))
print(meta_df.groupby(['split','label_binary']).size())
from google.colab import files
files.download(OUT_SQLITE)

